### ISSUE TITLE
Android Wear

### ISSUE THREAD

**Issue by PolarDog23** [StephenBlackWasAlreadyTaken/xDrip-Experimental#281]
Running on a Moto 360 Sport.  I noticed after the recent Marshmallow push to the watch last week, the Android Wear watch face no longer works. I get a note: "Unfortunately, XDrips Prefs has stopped.", and the watch face goes black.  Android wear buld MEC23G.  The app on the phone works just fine. Any thoughts?

**Comment by AdrianLxM** [comment]
I honestly don' know why that happens and cannot test it at the moment.
For the people that had these problems a factory reset (it won't reset the OS version and all apps will be pushed again from the phone) did help.

If you do this, please report back.

**Comment by AdrianLxM** [comment]
Thanks to @ladyviktoria I have a stacktrace of an exception that might cause it:

```
02-18 21:45:07.537 526-544/? I/ActivityManager: Displayed com.eveningoutpost.dexdrip/.NWPreferences: +938ms
02-18 21:46:00.062 6745-6745/? E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.eveningoutpost.dexdrip, PID: 6745
java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(pri=0 contentView=com.eveningoutpost.dexdrip/0x1090085 vibrate=[0,400,300,400,300,400] sound=null defaults=0x0 flags=0x0 color=0x00000000 vis=PRIVATE)
at android.app.NotificationManager.notify(NotificationManager.java:222)
at android.app.NotificationManager.notify(NotificationManager.java:194)
at com.eveningoutpost.dexdrip.BaseWatchFace.missedReadingAlert(BaseWatchFace.java:331)
at com.eveningoutpost.dexdrip.BaseWatchFace.onTimeChanged(BaseWatchFace.java:195)
at com.ustwo.clockwise.WatchFace.updateTimeAndInvalidate(WatchFace.java:251)
at com.ustwo.clockwise.WatchFace.access$100(WatchFace.java:55)
at com.ustwo.clockwise.WatchFace$WatchFaceEngine.onTimeTick(WatchFace.java:412)
at android.support.wearable.watchface.WatchFaceService$Engine.onCommand(WatchFaceService.java:202)
at android.service.wallpaper.WallpaperService$Engine.doCommand(WallpaperService.java:977)
at android.service.wallpaper.WallpaperService$IWallpaperEngineWrapper.executeMessage(WallpaperService.java:1191)
at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:37)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5422)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
02-18 21:46:00.077 526-537/? W/ActivityManager: Force finishing activity com.eveningoutpost.dexdrip/.NWPreferences
```

If that's the cause I hope to have a fix within the next couple of days.

**Comment by AdrianLxM** [comment]
@PolarDog23, if you give me your email adress (mine is adrian.m@inbox.com), I can send you an apk that hopefully has that fixed.
